spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 007shiyao
    driver-class-name: com.mysql.jdbc.Driver

