file-save-path: /usr/awmImages/
#file-save-path: D:/images/
server:
  port: 8082

spring:
  datasource:
#    name: awm #China server
#    url: jdbc:mysql://47.104.167.88:3306/awm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.jdbc.Driver
    name: awm #Sydney server
    url: jdbc:mysql://47.74.88.228:3306/awm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: smtp.qq.com # mail server
    username: 147573224@qq.com # email address
    password:  kklesabksidkbidj #Authorization code
    properties.mail.smtp.port: 465 # port 465 or 587
    from: 147573224@qq.com # email address
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

